services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ragops-postgres
    environment:
      POSTGRES_USER: ragops
      POSTGRES_PASSWORD: ragops
      POSTGRES_DB: ragops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ragops-redis
    ports:
      - "6379:6379"

  api:
    container_name: ragops-api
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
      target: api_runtime
    environment:
      RAGOPS_HTTP_ADDR: ":8080"
      RAGOPS_DATABASE_URL: "postgres://ragops:ragops@postgres:5432/ragops?sslmode=disable"
      RAGOPS_REDIS_ADDR: "redis:6379"
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  worker:
    container_name: ragops-worker
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
      target: worker_runtime
    environment:
      RAGOPS_DATABASE_URL: "postgres://ragops:ragops@postgres:5432/ragops?sslmode=disable"
      RAGOPS_REDIS_ADDR: "redis:6379"
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: ragops-prometheus
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

volumes:
  pgdata: